### PR TITLE
Programmatically create/populate/write DataSets

### PR DESCRIPTION
**Pull request by khaeru**
I know this isn't yet an official feature, but it's one I'd find useful.

In the spirit of a [main feature of the package](https://pandasdmx.readthedocs.io/en/latest/index.html#main-features) being a "Pythonic representation of the SDMX information model", the idea is to:
1. Programmatically create an empty `pandaSDMX.model.DataSet` (not read from any file or request).
2. Populate it with observations and other things from the data model.
3. Retrieve a `pd.Dataframe` using `pandaSDMX.data2pandas.Writer`.

I created a branch with a test to show how this would look. For the moment, it fails, because all subclasses of `SDMXObject` require `reader` and `elem` arguments. Some changes will be required to make this work; so I created this PR to, hopefully, discuss and iterate. (It is *not* remotely ready to merge, and won't be until the test passes.)

## API changes
Some of this might necessitate (or be a lot easier with) changes to the public API. I'll mention these here:

1. **Iteration vs. random access.** `DataSet.obs` and `Series.obs` will allow direct (random) access to individual observation; `DataSet.iter_obs(…)` and `Series.iter_obs(…)` will return iterators over the observations.

    The original focus on reading from files/streams meant individual series/options were parsed as they arrived. By using `iter_obs()`, users can keep this behaviour. If/when the `.obs` attribute is accessed, the entire `DataSet` or `Series` will be loaded and stored. We might want to add some tests for performance on large messages.

## Questions/issues
These concern (apparent) differences between the current pandaSDMX implementation and the [SDMX information model](https://sdmx.org/wp-content/uploads/SDMX_2-1-1_SECTION_2_InformationModel_201108.pdf).

1. **Information model:** §5.4, the Data Set diagram/description shows that 0+ AttributeValue can be attached to each of DataSet, Key (and thus SeriesKeys), and Observation. Each AttributeValue is associated to a DataAttribute given in the DSD. (Note: I am new to UML; can't tell if these associations are mandatory or optional.)

    **pandaSDMX:** includes a `model.DataAttribute` class, but it seems like `pandasdmx.reader.sdmxml` and `pandasdmx.reader.sdmxjson` create an `ObsAttributes` namedtuple that doesn't reference DataAttribute.

    **Proposed change:** Instead of a namedtuple, use a dict of AttributeValue objects. The dict keys will be names of the DataAttributes; this does not seem to be specified in the information model, but is a convenience/makes the implementation more Pythonic.

### CODE REVIEW

**Comment by dr-leo** [comment]
Paul,

this is a mind-blowing idea. Thumbs up! Add a writer for sdmxjson, and
you have a core part of an SDMX Server.

The downside is that I currently don't have much time to look at your
PR to say the least.

Some very preliminary thoughts on architecture; I am probably jumping
the gun, still the following might be inspiring; feel free to
contradict; happy to discuss here, but can't test / contribute Code.

I would probably think about
1. adding a ProgrammaticReader class to return the "injected"
artefacts (e.g. Series, Observation etc.), and
2. extend model.SDMXObject so that each instance can receive values
for the respective Attributes, properties etc. Maybe some Traits
mechanism would help which might be activated at instance level when
ProgrammaticReader is present. But some _inject method might be in
order as well. A Container dict to store the injected staff could make
sense.

Well, thinking about it, a dedicated Reader might as well Access a
proprietary Python data structure similar to what the stdlib json
would return, or lsml.objectify... In this case you wouldn't Need to
Change the model at all...

I guess you've considered the Option to cook up an SDMXJSON or sdmxml
file from your data and feed it into api.Request(fromfile=myfile).

Happy to discuss your further thoughts, if you accept my apologies in
advance for any nonsense due to lack of time on my side.

Leo



I would be interested to learn how you've approached the Problem from
an architecture Point of view.

If you're reluctant to enter into lengthy discussions with me (which
is fine), then

**Comment by dr-leo** [comment]
So the more I think about it the more I am convinced that the right place for this functionality is a new reader with an underlying machinery for generating Raw data as proprietary data structures that could then be exposed by the reader to the model. The model itself would not be changed at all and such an architecture. You could do all kinds of fancy things with such a design: for example you could fetch data from a SQL database or real time measurements from some sensors beer climate or traffic or the temperature of your bathwater. You could even use asynchronous features, all behind the scenes in the layer that is currently represented by The LXML and json path modules. I guess th such an approach would be at odds with your work so far. But this is my current view from scratch. Happy to hear about your views. As I said, I won’t be able to have a closer look on your code before mid November or even later. Sorry for that.
Leo

**Comment by khaeru** [comment]
Thanks for all these thoughts & encouragement, and of course there's no obligation to supervise closely.

As you can see from the commits so far, my first step is building a `reader.null.Reader` class, which should clarify exactly what the `model.SDMXObject` subclasses depend. I think `reader.BaseReader` is not (for now) a _true_ abstract base class, because both `reader.sdxmjson.Reader` and `reader.sdmxml.Reader` implement many of the same methods.

So, once that's done, we should have a clearer sense of the Reader API. And then, as you say, the choice is between:
1. Creating a Reader that "reads" nothing, or
2. Changing many of the `model.SDMXObject` some classes so that they _optionally_ read their contents…but if no Reader is available, they are simply instantiated in an "empty" state.

To me, Option 2 is a little more Pythonic. And while I defer to your knowledge of the spec, which is very verbose, I don't think the information model has Messages or DataSets bound tightly to a Reader. At least, when I ctrl+F for "Reader" in the ["Information Model" PDF](https://sdmx.org/wp-content/uploads/SDMX_2-1-1_SECTION_2_InformationModel_201108.pdf), there is no result.

Instead "readers" are necessitated by representations of SDMX objects in particular formats: XML, JSON, CSV, etc. _If_ (but only "if"!) one has an XML/JSON file, then of course some kind of Reader is needed to turn it into SDMXObjects. But those objects should also be able to exist independently of any Reader.

Anyway, this is more about architecture, and the practical matter is: how extensive are the code changes required? So I will keep hacking, and alert you when there is something worth looking at.

**Comment by dr-leo** [comment]
I have yet to respond to your proposal of replacing the namedtuple type to represent Attributes of a dataset, series or Observation by dict.

I tend to be opposed to this for the following reasons:

1. dict is Memory-inefficient as the Attribute names occur in each dict at least as a ref, even though they are the same for all series / obs. So namedtuple is better suited for this purpose. 
2. dict does not order items. Thus the order is unpredictable. This may not look like a big deal in case of Attributes. However, this would add randomness to the Output and break third Party Code, e.g. due to different iterating behavior of dict and tuple. Moreover, if one Extended this idea to series.key, this wouldn't work at all as dimensions are ordered by Position even in the SDMX Information model. Otherwise, SDMXJSON and structure-specific SDMXML wouldn't work. That said, I assume you are not proposing this. 
3. I do not see any benefit. namedtuple is pythonic. each namedtuple type has its own Name etc.
4. Implementing DataValue as a proper SDMX type inheriting from SDMXObject rather than using str does not seem efficient. I decided to use simple python types instead. I did the same for Observation which are represented as namedtuples as well. Note that These do not inherit from SDMXObject and thus do not allow granular Access to the underlying XML or json structure. This is all for Speed. And it has proven useful. 

 I haven't given much thought on the Diagramm in chap. 5.4 of the info model. However, it seems to me that pandaSDMX sets the attrib Attributes of dataset or series to None if there is nothing in the dataset, e.g. because all Attributes are attached at dataset Level rather than series. Note that observations do not have an attrib Attribute because in this case Attributes attached to an Observation are represented as named tuple items.

**Comment by khaeru** [comment]
Since this has spiraled into a full-on refactor :upside_down_face: I'm going to close this PR and open a new one for discussion!

**Pull request closed without merging**
