### PR TITLE
0.9 fix istat

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

Fixes two issues with Istat provider:

- add supportserieskeysonly
- support `none` values in series

### CODE REVIEW

**Comment by khaeru** [comment]
@ioggstream —thanks for the contribution! However, I note this PR is against a very old branch that probably should be deleted or at least renamed by @dr-leo to avoid confusion. `master` is the current focus of development, and ISTAT seems to be usable with the current code (see e.g. #135).

Also, there are no plans to make maintenance or bug fix release following 0.9, e.g. 0.9.1 or similar.

Can you please confirm that whatever queries you are trying to make work with `master` and, if so, close the PR? Thank you!

**Comment by ioggstream** [comment]
@khaeru thanks for your reply. I'll shed more light on that:)

At first I tried with the `1.0.0b2` tag but I had issues in processing a dataset (see https://gist.github.com/ioggstream/26f16903181f994727a34eb970a7608f )

I tried to figure out what was happening but didn't succeed as it was easier to patch the older version than the new one. I suspect the problem is similar and maybe with some guidance (eg. I'll provide you a pytest file) I can even create a patch.

I understood the issues in maintaining old code... if we can figure out how to make it work with 1.x it would be great!

**Comment by khaeru** [comment]
Great, thanks for this info.

> At first I tried with the `1.0.0b2` tag but I had issues in processing a dataset (see https://gist.github.com/ioggstream/26f16903181f994727a34eb970a7608f )

```
XMLParseError: KeyError: 'OBS_VALUE'

Stack:
GenericData
> DataSet
> Series

<generic:Obs xmlns:generic="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/generic" xmlns:footer="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message/footer" xmlns:message="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message" xmlns:common="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <generic:ObsDimension id="TIME_PERIOD" value="2005-01"/>
  <generic:Attributes>
    <generic:Value id="OBS_STATUS" value="c"/>
  </generic:Attributes>
</generic:Obs>
```

This definitely looks familiar. See https://github.com/dr-leo/pandaSDMX/blame/master/pandasdmx/reader/sdmxml.py#L882 —this was fixed by @guglielmo in #160, but only *after* 1.0.0b2 (21 January vs. 6 April). I would *like* to have released 1.0.0 or 1.0.0rc1 for you to try, but see #145 for why that hasn't happened yet.

This means you will need to try the code on `master`. One way you can do this, if using pip, is:
```
pip install git+git://github.com/dr-leo/pandaSDMX.git@master#egg=pandaSDMX
```

Can you please do this and see if your query succeeds?

**Comment by alinarello** [comment]
Hi,
I tryed with the code on master (version 1.0.0b2) and I have a problem with getting data from ISTAT
with keyError for OBS_VALUE. Is there a way to fix this?

XMLParseError: KeyError: 'OBS_VALUE'

Stack:
GenericData
> DataSet
> Series

<generic:Obs xmlns:generic="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/generic" xmlns:footer="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message/footer" xmlns:message="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message" xmlns:common="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <generic:ObsDimension id="TIME_PERIOD" value="2005-01"/>
  <generic:Attributes>
    <generic:Value id="OBS_STATUS" value="c"/>
  </generic:Attributes>
</generic:Obs>

**Comment by ioggstream** [comment]
@alinarello I created an istat testlist in this repo https://github.com/ioggstream/istat-rest-api-quickstart/blob/master/tests/test_queries_istat.yaml

First tests seem to work with the latest pandasdmx branch but I haven't still covered all possible queries: can you add your query to that repo so that the issue is reproducible?

**Comment by alinarello** [comment]
Hi @ioggstream ,

this is the query that fails (it's about data from the SBS that might contains confidential data). Below the error message:

`import pandasdmx as sdmx`
`istat = sdmx.Request('ISTAT')`
`data_response = istat.data(resource_id='161_267', key='A.9.12....11101', params=dict(startPeriod='2010', endPeriod='2010'))
`


`XMLParseError: KeyError: 'OBS_VALUE'

Stack:
GenericData
> DataSet
> Series

<generic:Obs xmlns:generic="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/generic" xmlns:footer="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message/footer" xmlns:message="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message" xmlns:common="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <generic:ObsDimension id="TIME_PERIOD" value="2010"/>
  <generic:Attributes>
    <generic:Value id="OBS_STATUS" value="c"/>
  </generic:Attributes>
</generic:Obs>
`

**Comment by ioggstream** [comment]
@alinarello ok, can you please file a PR to the repo? https://github.com/ioggstream/istat-rest-api-quickstart/blob/master/tests/test_queries_istat.yaml

**Comment by alinarello** [comment]
@ioggstream 
I am sorry but I am not an expert-user, not user I can make a PR. is this fine?
I did not try with other content-type.

**Comment by dr-leo** [comment]
Thanks for raising this. It is a Long Standing issue which should be tackled.

Could you pls retry with the recently released v1.0.0 and report the results?

**Comment by ioggstream** [comment]
@alinarello I'm using this one 

``` -e git+https://github.com/dr-leo/pandaSDMX.git@3d2507d6232132eb2313b0eba6f4e3c2423f742e#egg=pandaSDMX
```

**Comment by alinarello** [comment]
@dr-leo  version 1.0.0 is not available via pip install:

`ERROR: Could not find a version that satisfies the requirement pandasdmx==1.0.0 (from versions: 0.1, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7.0, 0.8, 0.8.1, 0.8.2, 0.9, 1.0b1, 1.0.0b2)
ERROR: No matching distribution found for pandasdmx==1.0.0`

**Comment by alinarello** [comment]
Hi @dr-leo ,
I have checked and with v1.0.0 it works fine.

**Comment by ioggstream** [comment]
Ok, let's close this!

**Pull request closed without merging**
