### PR TITLE
Refactor using typing & pydantic, improve testing, etc.

### PR DESCRIPTION
**Pull request by khaeru**
This PR grew out of #67, where the goal was to be able to create, populate, and write DataSets without reading them from file. This ended up needing a refactor of the pandaSDMX internals, to rigorously implement the [SDMX Information Model](https://sdmx.org/wp-content/uploads/SDMX_2-1-1_SECTION_2_InformationModel_201108.pdf) (the “IM”).

[`doc/whatsnew.rst`](https://github.com/khaeru/pandaSDMX/blob/refactor/doc/whatsnew.rst) is updated with a detailed description of the changes for users.

## Remaining tasks

This branch was started from `master`, which had not been updated since v0.7.0 (June 2017). With #73, `master` is again up to date, but more recent changes (v0.8.x and v0.9) show as merge conflicts. Resolve these by ensuring the PR code includes the following improvements:

- [x] ``doc/``: text additions in ``agencies.rst``, ``index.rst``, ``intro.rst``, ``sdmx_tour.rst``, ``usage.rst``
- [x] ``pandasdmx/api.py``: dsd and series_key args to get().
- [x] ``pandasdmx/model.py``: any useful functionality of new/updated classes…
   - [x] `KeyValidatorMixin`, `CodelistHandler`: these classes do not appear in the IM. Equivalent functionality is provided by implementing IM §10.3 Constraints.
   - [x] `Constrainable`, `CubeRegion`: the new version has more functionality.
   - [x] `ProvisionAgreement`.
- [x] ``pandasdmx/reader/sdmxml.py``: handle structure specific messages.
- [ ] ``pandasdmx/writer/data2pandas.py``: frequency/time series indices.
- [x] ``pandasdmx/writer/structure2pd.py``: constrained writing.

Address issues in `doc/roadmap.rst` under “Towards v1.0”, especially:
- [x] Update and add tests for `Request.preview_data()`.
- [x] Harmonize handling of API/network errors.
- [x] Remove `odo` as a dependency; *suggest* its use in the documentation.

## Notes
To help with review, because the repo is not configured to show these:
- Preview of the docs build: https://pandasdmx-dev.readthedocs.io/en/refactor/.
- ~Test results:~ working again after rebase.
  - ~https://travis-ci.org/khaeru/pandaSDMX/branches (until merge conflicts are resolved) or~
  - ~https://travis-ci.org/dr-leo/pandaSDMX/pull_requests.~
- Coverage report (94%): https://codecov.io/gh/khaeru/pandaSDMX/tree/refactor/pandasdmx
- 50 of 156 changed files are deletions in `tests/data/demography/xhtml/`, an unused copy of the XSD XHTML spec.

### CODE REVIEW

**Comment by dr-leo** [comment]
I hope to find the time to carefully look at your great work, and maybe to contribute some Code at some Point.

My main question on the model remains this: Is the choice of traitlets warranted given that we have the typing module, dataclasses and type validators such as pydantic? These techniques are state of the art and yield succinct code. I doubt that traitlets, while fit for purpose, I would very much prefer a modern Approach. Support for Py2 should be dropped btw. 

Leo

**Comment by khaeru** [comment]
> Support for Py2 should be dropped btw.

Glad you agree. Several other pieces of software I work on are doing so this year, because EOL is 2020-01-01. The branch disables testing on Python 2.7 and doesn't claim to support it; see the `doc/whatsnew.rst`

> Is the choice of traitlets warranted given that we have the typing module, dataclasses and type validators such as pydantic?

Thanks for the suggestion. I've spent a few minutes looking at [pydantic](https://pydantic-docs.helpmanual.io/), and will need to experiment a little to see whether/how a few traitlets tricks in the current code can be replicated. I will comment again when I have.

One note: this would involve setting minimum Python to 3.6, and probably 3.7 for the "forward references" feature. Is that acceptable?

**Comment by dr-leo** [comment]
I wasn't Aware that pydantic Forward refs require py3.7. Even so, I
tend to think requiring Py3.7 should be ok. It will take some time
until the next release anyway.

I haven't done any Research on whether pydantic is the best fit among
PEP484 toolkits.

**Comment by khaeru** [comment]
> I've spent a few minutes looking at [pydantic](https://pydantic-docs.helpmanual.io/), and will need to experiment a little to see whether/how a few traitlets tricks in the current code can be replicated.

Experimentally this seems to work! I filed samuelcolvin/pydantic#521 and samuelcolvin/pydantic#524 for                      some issues I discovered.

**Comment by dr-leo** [comment]
On #521: I don't get the rationale behind the current Approach which,
I think is not very pythonic. I would rather prefer not copying both
for Performance and because you can't avoid side effects only so far
by copying a Container type.

If the Approach since #154 is uncontestable, perhaps one can settle
for making the behavior configurable. That said, your subclassing
hack, if somewhat ugly, would do the trick, assuming you really Need
Attribute identity.

**Comment by khaeru** [comment]
Now that `master` is updated (#73) this will require a rebase.

**Comment by khaeru** [comment]
@dr-leo a note for future discussion:

> - [x] `pandasdmx/model.py`: any useful functionality of new/updated classes…
>   - [x]  `ProvisionAgreement`.

These are now parsed and made available in the `refactor` branch, but I would appreciate a pointer to (or test code for) a specific, real-world case where a ProvisionAgreement is used to constrain another object.

**Comment by khaeru** [comment]
Just rebased this onto the recently-updated `master` branch.

**Comment by khaeru** [comment]
Rebased, all tests passing, and ready to merge!

**Pull request merged**
