### PR TITLE
SDMXJSON tests & fixes

### PR DESCRIPTION
**Pull request by khaeru**
Adds `tests/tests_json.py`, which takes test coverage to ~80% for SDMXJSON.

In order to get the tests to pass for `tests/data/json/exr-flat.json`, I had to rewrite `iter_generic_obs`. I did this with reference to `iter_generic_series_obs` and minimal changes.

Two possible things I could see needing work before this can be merged:
- Use one private method for both `iter_generic_obs` and `iter_generic_series_obs`, since the code is very similar, and make the actual methods thin wrappers.
- `tests/data/json/exr-flat.json` seems to be loaded without the extra attributes (FREQ, CURRENCY_DENOM) etc. as MultiIndex levels—maybe this is because it's loaded as a `pd.Series`, and those are typically returned as levels on a columns `pd.MultiIndex` of a `pd.DataFrame`? If this should be handled some other way, happy to make the required changes.

### CODE REVIEW

**Comment by khaeru** [comment]
(Incidentally, if the above is annoying, I think there's a Codecov setting to prevent it from posting comments on pull requests.)

**Comment by dr-leo** [comment]
Thanks. 

On a private method: Yes, this would reduce Code duplication. But it would require a method call per obs, i.e. in the innermost Loop. This might Impact Performance. And due to my vague recollection, the private method would Need to distinguish some cases. That said, I leave it up to you. A private method called once per series rather than obs would be no Problem at all.

On the missing dimensions: A flat dataset has by Definition all Dimension values at Observation Level. Hence dim_at_obs == 'AllDimensions'. I recall the sdmxjson guys departed substantially from the SDMXML structure so I had to fiddle around to gloss over this difference at model Level, i.e. the dim_at_obs Attribute for DataSet. I believe the Header of an sdmxjson jessage has no dim_at_obs Attribute unlike the sdmxml case. So much for detection of flatness by the writer.

When I adapted the sdmxml Reader to sdmxjson I might have neglected iter_generic_obs as I did not care that much about flat datasets. But clearly this is a gap, thanks for closing it.

In case of a flat dataset, The writer should return a multi-indexed PD.Series with all dim values. Dimension names should be propagated to MultiIndex Level names. If it doesn't for sdmxjson whereas it does so for sdmxml, there is likely a Problem in the json reader.

**Comment by dr-leo** [comment]
Paul,

"
•  tests/data/json/exr-flat.json  seems to be loaded without the extra attributes (FREQ, CURRENCY_DENOM) etc. as MultiIndex levels—maybe this is because
it's loaded as a  pd.Series , and those are typically returned as levels on a columns  pd.MultiIndex  of a  pd.DataFrame ? If this should be handled some
other way, happy to make the required changes."

you can safely ignore my previous comment. It misses the point. The missing components ('FREQ', CURRENCY_DENOM' etc.) are dimensions, not attributes. The reason for this bug is that like with attributes, dimension values may be attached not only to each observation, but also to the dataset. The file in question is an example. So any dimension values must be fetched from the dataset before looping over the observations, and mixed with the obs-level dimension values. I did this for attributes in iter_generic_series_obs. Note the helper methods 'dataset_attributes' and 'series_attributes'. Similarly, a helper method for dataset_dimensions must be added and called by iter_generic_obs in case of flat datasets. I think that same method must be called by iter_generic_series_obs in case of series. The main difference between collecting attribute values and dimension values is that the latter are ordered by position. Hence, you cannot simply append the obs-level dimension values to those fetched from the series, if any, or dataset, or vice versa. Rather, you have to sort dimensions by position before creating the namedtuple type and looping over the observations. 

Note that dataset-level dimension values apply to all observations of a flat dataset and all series of a non-flat dataset. 
 
Further, there is likely a bug in the code generating the series keys for non-flat datasets: There, too, dataset-level dimension values must be fetched and combined with the series-level dimension values, preserving the dimension order as specified by the position attribute of each dimension.

I believe that in SDMXML, datasets may not have any dimension values; they may have attributes though. Rather, dimension values may be attached to series and groups of series (let alone the dimension of dimensions at obs-level).

Leo

**Comment by dr-leo** [comment]
Consider the series_key method for non-flat datasets:
- First, the series_key method pulls down any dataset dimensions. 
- Second, it gets the dimensions at series level. 
- Third, dataset dims and series dims are put together with extend(). This looks like a bug as the keyPosition is disregarded, hence dimension values in the series key may end up in the wrong order. 

For flat datasets you'd have to do almost the same. But instead of meshing dataset-level and series-level dims, you have to mesh dataset-level dims and obs-level dims according to their keyPosition attributes.

**Comment by khaeru** [comment]
Thanks, these explanations are really helpful in understanding the data model better. Will reference them as I work on the two outstanding items.

**Comment by Battiston** [comment]
Please delete me from your distribution list.

Thank you and best regards

Stefan Geisse

Induality®
Stressbewältigung, Gesundheit, persönliche Entwicklung
Minervastrasse 113
CH 8032 Zürich
www.induality.com
+41 78 659 86 40

Gestresst, Müde, Erschöpft?
Zeit für eine www.Stress-Auszeit.ch!
Kloster, Yogaferien, Detox und Ayurveda


------ Originalnachricht ------
Von: "dr-leo" <notifications@github.com>
An: "dr-leo/pandaSDMX" <pandaSDMX@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 05.04.2017 10:03:56
Betreff: Re: [dr-leo/pandaSDMX] SDMXJSON tests & fixes (#51)

**Comment by dr-leo** [comment]
I played around a bit with your code and fixed the issues identified including those in my code. Now, all files except 'action-delete' are handled properly. I won't implement action-delete files as I do not see merit in such feature. Still one of your tests fails even if I remove the 'action-delete' stuff. 

It appears I cannot push to your PR which may be due to missing permissions or my old habit to use hg with hg-git instead of git. Therefore I've pushed the code to my repo. 
 
Do you think you can adjust your tests in the coming weeks?

?

**Comment by khaeru** [comment]
Hi @dr-leo —sure, will return to this this week.

In the right column of this PR, I've checked the box "allow edits from maintainers," about which Github says "If checked, users with write access to **dr-leo/pandaSDMX** can add new commits to your `json-tests` branch. You can always change this setting later." So I'm not sure why you weren't able to do that.

It will take a little longer because the changes you made on the `master` branch seem to be inspired by, but not the same as, the commits on my branch. So I'll have to remember how to do a rebase—but again, should be able to wrap it up this week.

**Comment by dr-leo** [comment]
Oh sure, you gave me write privileges. But I don't know the URL maybe
some <repo-url>#<branch> notation. But they may differ between git and
hg... I give up at that point. I am such a bad github citizen... Apologies.


On rebasing: Yet another topic I refuse to spend time on. My advise
would be this: copy my sdmxjson.py into your branch and edit it as you
see fit, and update the test_json.py, then this can be merged.


I definitely worked on your version of sdmxjson. But admittedly I did
some terrible things. If you want to understand the code (which is
strictly not necessary to write great tests), you may want to consider
the following assumption I relied on:

- dimensions are ordered by keyPosition in the json dataset file.

- In case of time-series datasets, the key length (i.e. dim key-values
per series) is the sum of the number of series dims and dataset-level dims.

- For flat datasets, just add the number of dataset-level dims and
obs-level dims.

- for cross-sectional: there is exactly one dim at obs which has a
key-position, unlike the dim which ascended to the series level, eg.
time_period.


The code can be simplified a bit. But I am unaware of any bugs right
now. I think all the issues we discussed earlier are solved.


Leo












Am 02.05.2017 um 21:05 schrieb Paul Natsuo Kishimoto:

**Comment by khaeru** [comment]
In the end the rebase wasn't bad.

Additional changes:
- The JSON reader tests now put the dimensions in the correct order, as suggested by the comment about key positions.
- Re-enabled testing. The `requirements.txt` file had been moved.
- Added `doc/requirements.txt`. This one includes IPython; the top-level `requirements.txt` now omits it. This is because IPython>6 is not compatible with Python 2.7, but pandaSDMX doesn't use IPython for anything except building the docs. On the Read the Docs website, there is a setting that allows specifing the location of this file (the one in the `doc/` directory).

Also, on re-enabling testing, I noticed and fixed an error that showed up for Python 2.7 in `model.Dimension.__init__`. Here, `super()` is called without arguments, which is only available in Python 3.

The parent class, `Component`, doesn't have an `__init__` method, so what appears to be wanted is to call `IdentifiableArtefact.__init__`. So what we could do here is either:
1. call `super(Component, self)…` in this place, or
2. add a dependency on the [`future`](http://python-future.org) package and leave `super()` as is.

Which would you prefer, @dr-leo ? Please let me know, I'll add one more commit, and then we should be good to merge.

P.S. I notice that that line was changed in f5c6589c89ce11b4081aed390dc63c4e9f48d332, which has the comment "fix model.TimeDimension"—but the tests pass either way. Maybe after this is merged, someone can add a test for whatever that was?

**Comment by dr-leo** [comment]
Thanks.

On requirements.txt: I renamed it because this appeared as the
cheapest way to prevent automatic doc builds on every commit. It is
cleaner, of Course, to Show the docs as per the latest stable Version
rather than the latest dev Version. Bub I found it tedious to Change
Settings on readthedocs.io on each release. - I had the Impression
that doc/requirements.txt was checked by Default at first, then the
same file in the pkg root. So your fix should be fine, otherwise I'll
check the Settings as you suggest.

On the super() call in class DIMENSION: I had introduced that bug a
few days ago for being confused by some dimensions not having a
keyPosition Attribute in sdmx-json. As a wrote earlier: This Standard
is screwed up because of allowing keyPosition to be absent or NULL in
which case one has to infer the keyPosition.

Leo

**Pull request merged**
