### PR TITLE
Added missing placeholder for "format()"

### PR DESCRIPTION
**Pull request by toobaz**
This doesn't give any error... but doesn't print the list neither!

### CODE REVIEW

**Comment by toobaz** [comment]
Ehm... I must admit that only now I saw there was a "v0.3.2dev" branch with much more recent commits.

(I must also admit that I am not exactly a fan of how this project uses branches...)

This pull request (as well as the other I just made) is unchecked/untested in v.0.3.2dev (because of https://github.com/dr-leo/pandaSDMX/issues/22 )

**Comment by dr-leo** [comment]
Hi Pietro,

thanks a lot for all this.

I don't think my branch policy, if any, is acceptable by any standard. I
have a blind spot here as I am reluctant to delve into git. Locally I
work with Mercurial. This is no excuse, I know. But I had other
priorities so far.

Maybe I should commit to master only and tag each release rather than
open a branch unless I fiddle with stuff. So far I would have been
better of without any of those branches...

Leo


Am 04.11.2015 um 23:39 schrieb Pietro Battiston:

**Comment by dr-leo** [comment]
Done.

**Comment by toobaz** [comment]
Il giorno mer, 04/11/2015 alle 21.53 -0800, dr-leo ha scritto:
> [...]
> 
> Maybe I should commit to master only and tag each release rather than
> open a branch unless I fiddle with stuff. 

That would be great!

Then versioned branches in principle _can_ make sense (e.g. you want to
avoid experimental changes in "master" to affect a version you're about
to release, but still polishing, so the two must diverge), but in your
repo, currently, version-specific branches... never diverge! So they
are of no use, as far as I can tell.

(and in any case, I think it would be better to avoid giving the same
name to branches and tags)

Pietro

**Pull request closed without merging**
