### PR TITLE
Spec minimum Python version and test

### LINKED ISSUE #110: There is code only supported by Python 3.6+, while no Python version requirement is specified
There is line like https://github.com/dr-leo/pandaSDMX/blob/a31249da9a11e400a2b2f410d16e0010b4ff56af/pandasdmx/api.py#L145 which is using f-string and only supported by Python 3.6 and +.

However, there is no `python_requires` specified anywhere like `setup.py`.

So we need to either avoid using features like f-string which is only supported by the relatively new Python versions, or specify `python_requires` so users know they can only run the package using specific Python versions.

### PR DESCRIPTION
**Pull request by khaeru**
Closes #110.

### CODE REVIEW

**Comment by dr-leo** [comment]
Why not require Py3.7 and/or do without OrderedDict as dict preserves order as from Py3.6, officially though only from 3.7.Dropping 3.6 Support should be no Problem for most users, even more so when we release hopefully this year. We should Focus our Attention on Features, stability, Code clarity and to a lesser extent Performance.

**Comment by khaeru** [comment]
> Why not require Py3.7

I think that's a great idea, actually! I just didn't want to do so unilaterally.

I will update this branch accordingly. Meanwhile, a quick review (or "please go ahead without review") on #113 would be appreciated.

**Comment by khaeru** [comment]
> I will update this branch accordingly.

@dr-leo I did this on Tuesday—if you'd like me to go ahead and merge without review, please say so.

**Comment by dr-leo** [comment]
I haven't reviewed the Code but trust it will be good. So pls go merge it.

**Pull request merged**
